puts "Makers Academy 8th December 2014 Cohort"
puts "---------------------------------------"

puts "Sanda Golcea"
puts "Matteo Manzo"
puts "Bibiana Cristòfol"
puts "Steph Oldcorn"
puts "Huy Le"
puts "Kieran Goodacre"
puts "Emily Sas"
puts "India Dearlove"
puts "Jacob Mitchinson"
puts "Marcin Wal"
puts "Andy Newman"
puts "Richard Ighodaro"
puts "Ptolemy Barnes"
puts "Marcus de Wilde"
puts "Bebbs"
puts "Luke"
puts "Oliver Lucas"
puts "Jack Rubio"
puts "David Blake"
puts "Charlie Walsh"
puts "Danielle"
puts "Gabe"
puts "Jin Dai"
puts "Gus Powell"
puts "Jake Alvarez"
puts "Hannah Carney"
puts "Clint"
puts "Michael Colley"
puts "JJ Lakin"
puts "Will"